# 
# Copyright 2014 JackpotClavin
#
# Android Blob Utility
#

PRODUCT_COPY_FILES += \

vendor/i-mobile/i_mobile/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
vendor/i-mobile/i_mobile/proprietary/lib/libgybeauty.so:system/lib/libgybeauty.so \
vendor/i-mobile/i_mobile/proprietary/lib/libgybeauty420sp_2.so:system/lib/libgybeauty420sp_2.so \
warning: blob file libgybeauty422.so missing or broken
warning: blob file libgybeauty420.so missing or broken
vendor/i-mobile/i_mobile/proprietary/lib/libgybeauty420sp.so:system/lib/libgybeauty420sp.so \
warning: blob file libgy_effect.so missing or broken
warning: blob file libgy_hdr.so missing or broken
vendor/i-mobile/i_mobile/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
vendor/i-mobile/i_mobile/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
vendor/i-mobile/i_mobile/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
warning: blob file libfcvopt.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libqdMetaData.so:system/lib64/libqdMetaData.so \
vendor/i-mobile/i_mobile/proprietary/lib/libqdMetaData.so:system/lib/libqdMetaData.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
vendor/i-mobile/i_mobile/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libgps.utils.so:system/lib64/libgps.utils.so \
vendor/i-mobile/i_mobile/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libloc_core.so:system/lib64/libloc_core.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
vendor/i-mobile/i_mobile/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
warning: blob file libloc_api-rpc-qc.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
warning: blob file libizat_api_pds.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
vendor/i-mobile/i_mobile/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libloc_eng.so:system/lib64/libloc_eng.so \
vendor/i-mobile/i_mobile/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
vendor/i-mobile/i_mobile/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
vendor/i-mobile/i_mobile/proprietary/bin/app_process:system/bin/app_process \
vendor/i-mobile/i_mobile/proprietary/bin/app_process32:system/bin/app_process32 \
vendor/i-mobile/i_mobile/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
warning: blob file libmmcamera_tuning.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
warning: wildcard lib%s_skel.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
warning: blob file libfcvopt.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
warning: blob file libmmcamera_cac2_lib.so missing or broken
warning: blob file libmmcamera_fssr_lib.so missing or broken
warning: blob file libmmcamera_dummyalgo.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
warning: blob file libtbbmalloc.so missing or broken
warning: blob file libirml.so missing or broken
warning: blob file libmmcamera_llvd.so missing or broken
warning: blob file libmmcamera_trueportrait_lib.so missing or broken
warning: blob file libmmcamera_multitouchfocus_lib.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:system/vendor/lib64/libmmcamera2_frame_algorithm.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
warning: blob file libc2d2.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_imx214.so:system/vendor/lib64/libmmcamera_imx214.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_common.so:system/vendor/lib64/libchromatix_imx214_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_snapshot.so:system/vendor/lib64/libchromatix_imx214_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_default_video.so:system/vendor/lib64/libchromatix_imx214_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_liveshot.so:system/vendor/lib64/libchromatix_imx214_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_liveshot.so:system/vendor/lib/libchromatix_imx214_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_preview.so:system/vendor/lib64/libchromatix_imx214_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_video_1080p.so:system/vendor/lib64/libchromatix_imx214_video_1080p.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_video_1080p.so:system/vendor/lib/libchromatix_imx214_video_1080p.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_hfr_60fps.so:system/vendor/lib64/libchromatix_imx214_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_hfr_90fps.so:system/vendor/lib64/libchromatix_imx214_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_hfr_90fps.so:system/vendor/lib/libchromatix_imx214_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_hfr_120fps.so:system/vendor/lib64/libchromatix_imx214_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_hfr_120fps.so:system/vendor/lib/libchromatix_imx214_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_video_hdr.so:system/vendor/lib64/libchromatix_imx214_video_hdr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib64/libchromatix_imx214_snapshot_hdr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_imx220.so:system/vendor/lib64/libmmcamera_imx220.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx220_common.so:system/vendor/lib64/libchromatix_imx220_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx220_common.so:system/vendor/lib/libchromatix_imx220_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx220_snapshot.so:system/vendor/lib64/libchromatix_imx220_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx220_snapshot.so:system/vendor/lib/libchromatix_imx220_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx220_preview.so:system/vendor/lib64/libchromatix_imx220_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx220_preview.so:system/vendor/lib/libchromatix_imx220_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx220.so:system/vendor/lib/libmmcamera_imx220.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_ov16825.so:system/vendor/lib64/libmmcamera_ov16825.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov16825_common.so:system/vendor/lib64/libchromatix_ov16825_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov16825_common.so:system/vendor/lib/libchromatix_ov16825_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov16825_snapshot.so:system/vendor/lib64/libchromatix_ov16825_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov16825_snapshot.so:system/vendor/lib/libchromatix_ov16825_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov16825_default_video.so:system/vendor/lib64/libchromatix_ov16825_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov16825_default_video.so:system/vendor/lib/libchromatix_ov16825_default_video.so \
warning: blob file libchromatix_ov16825_liveshot.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov16825_preview.so:system/vendor/lib64/libchromatix_ov16825_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov16825_preview.so:system/vendor/lib/libchromatix_ov16825_preview.so \
warning: blob file libchromatix_ov16825_hfr_60fps.so missing or broken
warning: blob file libchromatix_ov16825_hfr_120fps.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov16825.so:system/vendor/lib/libmmcamera_ov16825.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_ov5670_g04a.so:system/vendor/lib64/libmmcamera_ov5670_g04a.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_common.so:system/vendor/lib64/libchromatix_ov5670_g04a_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_common.so:system/vendor/lib/libchromatix_ov5670_g04a_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_zsl.so:system/vendor/lib64/libchromatix_ov5670_g04a_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_zsl.so:system/vendor/lib/libchromatix_ov5670_g04a_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_snapshot.so:system/vendor/lib64/libchromatix_ov5670_g04a_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_snapshot.so:system/vendor/lib/libchromatix_ov5670_g04a_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_default_video.so:system/vendor/lib64/libchromatix_ov5670_g04a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_default_video.so:system/vendor/lib/libchromatix_ov5670_g04a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_liveshot.so:system/vendor/lib64/libchromatix_ov5670_g04a_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_liveshot.so:system/vendor/lib/libchromatix_ov5670_g04a_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_preview.so:system/vendor/lib64/libchromatix_ov5670_g04a_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_preview.so:system/vendor/lib/libchromatix_ov5670_g04a_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_hfr_60fps.so:system/vendor/lib64/libchromatix_ov5670_g04a_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_g04a_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_hfr_90fps.so:system/vendor/lib64/libchromatix_ov5670_g04a_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_g04a_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov5670_g04a_hfr_120fps.so:system/vendor/lib64/libchromatix_ov5670_g04a_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_g04a_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_g04a_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5670_g04a.so:system/vendor/lib/libmmcamera_ov5670_g04a.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_ov7695.so:system/vendor/lib64/libmmcamera_ov7695.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov7695.so:system/vendor/lib/libmmcamera_ov7695.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_ov8858.so:system/vendor/lib64/libmmcamera_ov8858.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_common.so:system/vendor/lib64/libchromatix_ov8858_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_snapshot.so:system/vendor/lib64/libchromatix_ov8858_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_default_video.so:system/vendor/lib64/libchromatix_ov8858_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_liveshot.so:system/vendor/lib64/libchromatix_ov8858_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_preview.so:system/vendor/lib64/libchromatix_ov8858_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_ov8858_q8v19w.so:system/vendor/lib64/libmmcamera_ov8858_q8v19w.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib/libchromatix_ov8858_q8v19w_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib/libchromatix_ov8858_q8v19w_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov8858_q8v19w.so:system/vendor/lib/libmmcamera_ov8858_q8v19w.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_qtech_ov5670_eeprom.so:system/vendor/lib64/libmmcamera_qtech_ov5670_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_qtech_ov5670_eeprom.so:system/vendor/lib/libmmcamera_qtech_ov5670_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_qtech_ov8858_eeprom.so:system/vendor/lib64/libmmcamera_qtech_ov8858_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_qtech_ov8858_eeprom.so:system/vendor/lib/libmmcamera_qtech_ov8858_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_sonyimx220_eeprom.so:system/vendor/lib64/libmmcamera_sonyimx220_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sonyimx220_eeprom.so:system/vendor/lib/libmmcamera_sonyimx220_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera_t4kb3.so:system/vendor/lib64/libmmcamera_t4kb3.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_common.so:system/vendor/lib64/libchromatix_t4kb3_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_common.so:system/vendor/lib/libchromatix_t4kb3_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_zsl.so:system/vendor/lib64/libchromatix_t4kb3_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_zsl.so:system/vendor/lib/libchromatix_t4kb3_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_snapshot.so:system/vendor/lib64/libchromatix_t4kb3_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_snapshot.so:system/vendor/lib/libchromatix_t4kb3_snapshot.so \
warning: blob file libchromatix_t4kb3_liveshot.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_preview.so:system/vendor/lib64/libchromatix_t4kb3_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_preview.so:system/vendor/lib/libchromatix_t4kb3_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_default_video.so:system/vendor/lib64/libchromatix_t4kb3_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_default_video.so:system/vendor/lib/libchromatix_t4kb3_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_hfr_60fps.so:system/vendor/lib64/libchromatix_t4kb3_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_hfr_60fps.so:system/vendor/lib/libchromatix_t4kb3_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_hfr_90fps.so:system/vendor/lib64/libchromatix_t4kb3_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_hfr_90fps.so:system/vendor/lib/libchromatix_t4kb3_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_t4kb3_hfr_120fps.so:system/vendor/lib64/libchromatix_t4kb3_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_t4kb3_hfr_120fps.so:system/vendor/lib/libchromatix_t4kb3_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_t4kb3.so:system/vendor/lib/libmmcamera_t4kb3.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_S5K4E1_13P1BA.so:system/vendor/lib/libmmcamera_S5K4E1_13P1BA.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_altek_le2464_eeprom.so:system/vendor/lib/libmmcamera_altek_le2464_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_gc0310.so:system/vendor/lib/libmmcamera_gc0310.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx135_liveshot.so:system/vendor/lib64/libchromatix_imx135_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_liveshot.so:system/vendor/lib/libchromatix_imx135_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx214_br.so:system/vendor/lib/libmmcamera_imx214_br.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_br_common.so:system/vendor/lib64/libchromatix_imx214_br_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_br_common.so:system/vendor/lib/libchromatix_imx214_br_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_br_snapshot.so:system/vendor/lib64/libchromatix_imx214_br_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_br_snapshot.so:system/vendor/lib/libchromatix_imx214_br_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_imx214_br_preview.so:system/vendor/lib64/libchromatix_imx214_br_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_imx214_br_preview.so:system/vendor/lib/libchromatix_imx214_br_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_imx214_bs.so:system/vendor/lib/libmmcamera_imx214_bs.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov13850_default_video.so:system/vendor/lib64/libchromatix_ov13850_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov13850_q13v06k.so:system/vendor/lib/libmmcamera_ov13850_q13v06k.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_common.so:system/vendor/lib/libchromatix_ov13850_q13v06k_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_snapshot.so:system/vendor/lib/libchromatix_ov13850_q13v06k_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_preview.so:system/vendor/lib/libchromatix_ov13850_q13v06k_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov13850_q13v06k_default_video.so:system/vendor/lib64/libchromatix_ov13850_q13v06k_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_default_video.so:system/vendor/lib/libchromatix_ov13850_q13v06k_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov13850_r2a.so:system/vendor/lib/libmmcamera_ov13850_r2a.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_r2a_common.so:system/vendor/lib/libchromatix_ov13850_r2a_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_r2a_snapshot.so:system/vendor/lib/libchromatix_ov13850_r2a_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_r2a_preview.so:system/vendor/lib/libchromatix_ov13850_r2a_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov13850_r2a_default_video.so:system/vendor/lib64/libchromatix_ov13850_r2a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_r2a_default_video.so:system/vendor/lib/libchromatix_ov13850_r2a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov13850_r2a_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_r2a_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov2680_cht852b.so:system/vendor/lib/libmmcamera_ov2680_cht852b.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_cht852b_common.so:system/vendor/lib/libchromatix_ov2680_cht852b_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_cht852b_snapshot.so:system/vendor/lib/libchromatix_ov2680_cht852b_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2680_cht852b_default_video.so:system/vendor/lib/libchromatix_ov2680_cht852b_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov2685.so:system/vendor/lib/libmmcamera_ov2685.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5648_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_p5v18g.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_p5v18g_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_p5v18g_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5648_q5v22e.so:system/vendor/lib/libmmcamera_ov5648_q5v22e.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5670_30010a3.so:system/vendor/lib/libmmcamera_ov5670_30010a3.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_common.so:system/vendor/lib/libchromatix_ov5670_30010a3_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_zsl.so:system/vendor/lib/libchromatix_ov5670_30010a3_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_snapshot.so:system/vendor/lib/libchromatix_ov5670_30010a3_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_default_video.so:system/vendor/lib/libchromatix_ov5670_30010a3_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_liveshot.so:system/vendor/lib/libchromatix_ov5670_30010a3_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_preview.so:system/vendor/lib/libchromatix_ov5670_30010a3_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_30010a3_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_30010a3_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_30010a3_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov5670_qc700.so:system/vendor/lib/libmmcamera_ov5670_qc700.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_common.so:system/vendor/lib/libchromatix_ov5670_qc700_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_zsl.so:system/vendor/lib/libchromatix_ov5670_qc700_zsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_snapshot.so:system/vendor/lib/libchromatix_ov5670_qc700_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_default_video.so:system/vendor/lib/libchromatix_ov5670_qc700_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_liveshot.so:system/vendor/lib/libchromatix_ov5670_qc700_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov5670_qc700_preview.so:system/vendor/lib/libchromatix_ov5670_qc700_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8865_q8v18a_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_qtech_ov13850_r2a_eeprom.so:system/vendor/lib/libmmcamera_qtech_ov13850_r2a_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_qtech_ov5648_eeprom.so:system/vendor/lib/libmmcamera_qtech_ov5648_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
warning: blob file libchromatix_skuf_ov12830_p12v01c_liveshot.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sonyimx135_eeprom.so:system/vendor/lib/libmmcamera_sonyimx135_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sonyimx214_eeprom.so:system/vendor/lib/libmmcamera_sonyimx214_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so:system/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so:system/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_toshiba_st1382_eeprom.so:system/vendor/lib/libmmcamera_toshiba_st1382_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
vendor/i-mobile/i_mobile/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_dw9714.so:system/vendor/lib64/libactuator_dw9714.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_dw9714_camcorder.so:system/vendor/lib64/libactuator_dw9714_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_dw9714_camera.so:system/vendor/lib64/libactuator_dw9714_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898122.so:system/vendor/lib64/libactuator_lc898122.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898122.so:system/vendor/lib/libactuator_lc898122.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898122_camcorder.so:system/vendor/lib64/libactuator_lc898122_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898122_camcorder.so:system/vendor/lib/libactuator_lc898122_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898122_camera.so:system/vendor/lib64/libactuator_lc898122_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898122_camera.so:system/vendor/lib/libactuator_lc898122_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898212.so:system/vendor/lib64/libactuator_lc898212.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898212.so:system/vendor/lib/libactuator_lc898212.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898212_camcorder.so:system/vendor/lib64/libactuator_lc898212_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898212_camcorder.so:system/vendor/lib/libactuator_lc898212_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_lc898212_camera.so:system/vendor/lib64/libactuator_lc898212_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_lc898212_camera.so:system/vendor/lib/libactuator_lc898212_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz.so:system/vendor/lib64/libactuator_rohm_bu64243gwz.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_214.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_214.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_214.so:system/vendor/lib/libactuator_rohm_bu64243gwz_214.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_214_camcorder.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_214_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_214_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_214_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_214_camera.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_214_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_214_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_214_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_ov13850.so:system/vendor/lib/libactuator_rohm_bu64243gwz_ov13850.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850_camcorder.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_ov13850_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_ov13850_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850_camera.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_ov13850_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_ov13850_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_ov13850_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3.so:system/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3_camcorder.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3_camera.so:system/vendor/lib64/libactuator_rohm_bu64243gwz_t4kb3_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_t4kb3_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_bu64297_q13v06k.so:system/vendor/lib/libactuator_bu64297_q13v06k.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so:system/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camera.so:system/vendor/lib/libactuator_bu64297_q13v06k_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_pc0fe.so:system/vendor/lib/libactuator_dw9714_pc0fe.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so:system/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camera.so:system/vendor/lib/libactuator_dw9714_pc0fe_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libois_lc898122.so:system/vendor/lib64/libois_lc898122.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libois_lc898122.so:system/vendor/lib/libois_lc898122.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
vendor/i-mobile/i_mobile/proprietary/bin/tftp_server:system/bin/tftp_server \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/bin/time_daemon:system/bin/time_daemon \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/bin/rmt_storage:system/bin/rmt_storage \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/i-mobile/i_mobile/proprietary/bin/radish:system/bin/radish \
vendor/i-mobile/i_mobile/proprietary/bin/qseecomd:system/bin/qseecomd \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsecureui.so:system/vendor/lib64/libsecureui.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/lib-sec-disp.so:system/vendor/lib64/lib-sec-disp.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libStDrvInt.so:system/vendor/lib64/libStDrvInt.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsecureui_svcsock.so:system/vendor/lib64/libsecureui_svcsock.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
warning: blob file libfwlock.so missing or broken
vendor/i-mobile/i_mobile/proprietary/bin/qmuxd:system/bin/qmuxd \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/bin/netmgrd:system/bin/netmgrd \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libcnefeatureconfig.so:system/lib64/libcnefeatureconfig.so \
vendor/i-mobile/i_mobile/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/i-mobile/i_mobile/proprietary/lib64/librmnetctl.so:system/lib64/librmnetctl.so \
vendor/i-mobile/i_mobile/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
vendor/i-mobile/i_mobile/proprietary/bin/irsc_util:system/bin/irsc_util \
vendor/i-mobile/i_mobile/proprietary/bin/wcnss_service:system/bin/wcnss_service \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
warning: blob file libGLESv2S3D_adreno.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsc-a2xx.so:system/vendor/lib64/libsc-a2xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libEGL_adreno.so:system/vendor/lib64/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libEGL_adreno.so:system/vendor/lib/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libEGL_adreno.so:system/vendor/lib64/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libEGL_adreno.so:system/vendor/lib/libEGL_adreno.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libaudioroute.so:system/lib64/libaudioroute.so \
vendor/i-mobile/i_mobile/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
vendor/i-mobile/i_mobile/proprietary/lib64/hw/audio.primary.default.so:system/lib64/hw/audio.primary.default.so \
vendor/i-mobile/i_mobile/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
vendor/i-mobile/i_mobile/proprietary/lib64/hw/audio.primary.msm8916.so:system/lib64/hw/audio.primary.msm8916.so \
vendor/i-mobile/i_mobile/proprietary/lib64/libtinycompress.so:system/lib64/libtinycompress.so \
vendor/i-mobile/i_mobile/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
warning: blob file libqcomvisualizer.so missing or broken
warning: blob file libqcompostprocbundle.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
warning: blob file libsurround_proc.so missing or broken
vendor/i-mobile/i_mobile/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
vendor/i-mobile/i_mobile/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so \
vendor/i-mobile/i_mobile/proprietary/lib/hw/audio.primary.msm8916.so:system/lib/hw/audio.primary.msm8916.so \